### ISSUE TITLE
Frage: Alignment CEF eDelivery?

### ISSUE THREAD

**Issue by phax** [austriapro/e-zustellung#1]
Hallo liebe e-Zusteller,

ich wollte fragen, ob es national irgendwelche Ambitionen gibt unsere Lösung mit der EU-Lösung (https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eDelivery) zu alignen???

(ich bin mir bewusst, dass das tendentiell das falsche Forum ist...)
Danke

**Comment by CarolaZentara** [comment]
Lieber Philip Helger,
du kannst dich gerne via zentara@postserver.com direkt an uns wenden :)

Beste Grüße,
Carola Zentara
